[package]
name = "remove_dir_all_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remove_dir_all = "0.7"
tempfile = "*"